import type Database from '@tauri-apps/plugin-sql';

interface Migration {
  version: number;
  name: string;
  statements: string[];
}

const migrations: Migration[] = [
  {
    version: 1,
    name: 'baseline_postgres_v1',
    statements: [
      `
        CREATE TABLE IF NOT EXISTS users (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username TEXT UNIQUE NOT NULL,
          password_hash TEXT NOT NULL,
          role TEXT NOT NULL CHECK (role IN ('admin', 'medico', 'infermiere')),
          nome TEXT NOT NULL,
          cognome TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `,
      `
        CREATE TABLE IF NOT EXISTS ambulatori (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nome TEXT NOT NULL,
          logo_path TEXT,
          color_primary TEXT NOT NULL DEFAULT '#1e3a8a',
          color_secondary TEXT NOT NULL DEFAULT '#3b82f6',
          color_accent TEXT NOT NULL DEFAULT '#22d3ee',
          indirizzo TEXT,
          telefono TEXT,
          email TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `,
      `
        CREATE TABLE IF NOT EXISTS pazienti (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ambulatorio_id INTEGER NOT NULL REFERENCES ambulatori(id) ON DELETE CASCADE,
          nome TEXT NOT NULL,
          cognome TEXT NOT NULL,
          data_nascita DATE NOT NULL,
          luogo_nascita TEXT NOT NULL,
          codice_fiscale TEXT NOT NULL,
          sesso TEXT NOT NULL CHECK (sesso IN ('M', 'F', 'Altro')),
          esenzioni TEXT,
          indirizzo TEXT,
          citta TEXT,
          cap TEXT,
          provincia TEXT,
          telefono TEXT,
          email TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `,
      `
        CREATE TABLE IF NOT EXISTS visite (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ambulatorio_id INTEGER NOT NULL REFERENCES ambulatori(id) ON DELETE CASCADE,
          paziente_id INTEGER NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,
          medico_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          data_visita TIMESTAMP NOT NULL,
          tipo_visita TEXT NOT NULL,
          motivo TEXT NOT NULL,
          altezza REAL,
          peso REAL,
          bmi REAL,
          bsa REAL,
          anamnesi_cardiologica TEXT,
          anamnesi_internistica TEXT,
          terapia_domiciliare TEXT,
          valutazione_odierna TEXT,
          esami_ematici TEXT,
          ecocardiografia TEXT,
          fh_assessment TEXT,
          terapia_ipolipemizzante TEXT,
          valutazione_rischio_cv TEXT,
          firme_visita TEXT,
          pianificazione_followup TEXT,
          conclusioni TEXT,
          anamnesi TEXT,
          esame_obiettivo TEXT,
          diagnosi TEXT,
          terapia TEXT,
          note TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `,
      `
        CREATE TABLE IF NOT EXISTS fattori_rischio_cv (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          visita_id INTEGER NOT NULL REFERENCES visite(id) ON DELETE CASCADE,
          familiarita BOOLEAN NOT NULL DEFAULT FALSE,
          familiarita_note TEXT,
          ipertensione BOOLEAN NOT NULL DEFAULT FALSE,
          diabete BOOLEAN NOT NULL DEFAULT FALSE,
          diabete_durata TEXT,
          diabete_tipo TEXT NOT NULL DEFAULT '',
          dislipidemia BOOLEAN NOT NULL DEFAULT FALSE,
          obesita BOOLEAN NOT NULL DEFAULT FALSE,
          fumo TEXT NOT NULL DEFAULT '',
          fumo_ex_eta TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `,
      `
        CREATE INDEX IF NOT EXISTS idx_pazienti_ambulatorio
        ON pazienti(ambulatorio_id)
      `,
      `
        CREATE INDEX IF NOT EXISTS idx_pazienti_cognome
        ON pazienti(cognome)
      `,
      `
        CREATE INDEX IF NOT EXISTS idx_pazienti_cf
        ON pazienti(codice_fiscale)
      `,
      `
        CREATE INDEX IF NOT EXISTS idx_visite_ambulatorio
        ON visite(ambulatorio_id)
      `,
      `
        CREATE INDEX IF NOT EXISTS idx_visite_paziente
        ON visite(paziente_id)
      `,
      `
        CREATE INDEX IF NOT EXISTS idx_visite_data
        ON visite(data_visita)
      `,
      `
        CREATE INDEX IF NOT EXISTS idx_fattori_rischio_visita
        ON fattori_rischio_cv(visita_id)
      `
    ]
  },
  {
    version: 2,
    name: 'data_imports_v2',
    statements: [
      `
        CREATE TABLE IF NOT EXISTS data_imports (
          name TEXT PRIMARY KEY,
          details TEXT,
          imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `
    ]
  }
];

export async function applyMigrations(db: Database): Promise<void> {
  await db.execute(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      version INTEGER PRIMARY KEY,
      name TEXT NOT NULL,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  const appliedRows = await db.select<Array<{ version: number | string }>>(
    'SELECT version FROM schema_migrations ORDER BY version'
  );
  const appliedVersions = new Set(appliedRows.map((row) => Number(row.version)));

  for (const migration of migrations) {
    if (appliedVersions.has(migration.version)) {
      continue;
    }

    for (const statement of migration.statements) {
      await db.execute(statement);
    }

    await db.execute(
      'INSERT INTO schema_migrations (version, name) VALUES ($1, $2)',
      [migration.version, migration.name]
    );
  }
}
